server:
  port: 8080

spring:
  application:
    name: AuthServices

  datasource:
    url: jdbc:mysql://localhost:3306/authdatabase
    username: root
    password: Vishal#184200
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

debug: true