server:
  port: 8081 # This will run the service on port 8081

spring:
  application:
    name: settings-service # Name of the microservice
  datasource:
    url: jdbc:mysql://localhost:3306/settings_db # Change according to your MySQL setup
    username: root
    password: "Vishal#184200"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka Server
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
